### ISSUE TITLE
incorrect name

### ISSUE THREAD

**Issue by hvoss49** [LineIndent/flet_projects#1]
With the file `ft_advanced_forms_heet/form.py` we get:

```
voss>ft_advanced_form_sheet:$ python3 form.py 
Traceback (most recent call last):
  File "/private/tmp/flet_projects/ft_advanced_form_sheet/form.py", line 190, in <module>
    ft.flet.app(target=main)
    ^^^^^^^
AttributeError: module 'flet' has no attribute 'flet'

```

That should be `ft.app(target=main)`

**Comment by Karthik7090ps** [comment]
> With the file `ft_advanced_forms_heet/form.py` we get:
> 
> ```
> voss>ft_advanced_form_sheet:$ python3 form.py 
> Traceback (most recent call last):
>   File "/private/tmp/flet_projects/ft_advanced_form_sheet/form.py", line 190, in <module>
>     ft.flet.app(target=main)
>     ^^^^^^^
> AttributeError: module 'flet' has no attribute 'flet'
> ```
> 
> That should be `ft.app(target=main)`

this helped me, thanks
